"""Add foreign keys to user profiles

Revision ID: 64e8ad8cd10a
Revises: dbe2cb3a96e7
Create Date: 2025-12-24 10:07:22.788317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e8ad8cd10a'
down_revision = 'dbe2cb3a96e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'buyers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sellers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'buyers', type_='foreignkey')
    # ### end Alembic commands ###

